# Generated by Django 5.0.4 on 2024-04-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('movement_direction', models.IntegerField(choices=[(1, 'forward'), (2, 'backward'), (3, 'stay')])),
                ('task', models.IntegerField(choices=[(0, 'None'), (1, 'moving'), (2, 'recharge'), (3, 'cleaning')])),
                ('battery_capacity', models.FloatField()),
                ('battery_durability', models.FloatField()),
                ('light_state', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'disabled'), (1, 'auto'), (2, 'handled')])),
            ],
        ),
    ]
