# Generated by Django 5.0.4 on 2024-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotsinfo',
            name='movement_direction',
            field=models.CharField(choices=[('forward', 'forward'), ('backward', 'backward'), ('stay', 'stay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='robotsinfo',
            name='status',
            field=models.CharField(choices=[('disabled', 'disabled'), ('auto', 'auto'), ('handled', 'handled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='robotsinfo',
            name='task',
            field=models.CharField(choices=[('None', 'None'), ('moving', 'moving'), ('recharge', 'recharge'), ('cleaning', 'cleaning')], max_length=50),
        ),
    ]
