# Generated by Django 5.0.4 on 2024-04-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_botdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotData',
            new_name='RobotsData',
        ),
    ]
